db_configs:

  kernelci.org:
    db_type: kernelci_backend
    url: https://api.kernelci.org/

  staging.kernelci.org:
    db_type: kernelci_backend
    url: https://api.staging.kernelci.org/

  chromeos.kernelci.org:
    db_type: kernelci_backend
    url: https://api.chromeos.kernelci.org/

  localhost:
    db_type: kernelci_backend
    url: http://localhost:5001/
